version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: