# ===== PROMETHEUS CONFIGURATION - NEW =====
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# ===== SCRAPE CONFIGURATIONS =====
scrape_configs:
  # ===== FINSIGHT SERVER METRICS =====
  - job_name: "finsight-server"
    static_configs:
      - targets: ["server:5000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # ===== PROMETHEUS SELF-MONITORING =====
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ===== SYSTEM METRICS =====
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

  # ===== REDIS METRICS (if redis_exporter is added) =====
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
# ===== ALERTING RULES (optional) =====
# rule_files:
#   - "alert_rules.yml"

# ===== ALERTMANAGER CONFIGURATION (optional) =====
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
