apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: finsight
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "admin" | base64
  # echo -n "password" | base64
  # echo -n "finsight_user" | base64
  # echo -n "finsight_password" | base64
  root-username: YWRtaW4=
  root-password: cGFzc3dvcmQ=
  username: Zmluc2lnaHRfdXNlcg==
  password: Zmluc2lnaHRfcGFzc3dvcmQ=
